package generator

import "text/template"

var generatedFileTemplate = template.Must(template.New("fieldops").Parse(`// Code generated by protoc-gen-fieldops. DO NOT EDIT.

package {{.PackageName}}

import fieldops "github.com/lfreixial/proto-opscope/pkg/fieldops"

// filteredFileDescriptor contains the pre-computed filtered file descriptor
// with synthetic message types for operation-scoped gRPC reflection.
var filteredFileDescriptor = []byte{
	{{.DescBytesLiteral}}
}

func init() {
	fieldops.AddDescriptor(filteredFileDescriptor)
}
`))
